### ISSUE TITLE
[BUG] Unable to upload any customization images

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#40] opened 2023-12-08 22:43 UTC
**Describe the Bug**
Not sure if the title explains it correctly, sorry!
I can upload art, but anything else (Icons, cover photos, backgrounds, page dolls, etc) seem to not be working.
It works fine in my Vivaldi browser.

**To Reproduce**
1. Go to any customization
2. Click "browse"
3. Click "select your new [x] image"
4. Nothing.

**Expected Behaviour**
I should get a window to select the file I want to upload.

**Screenshots**
Video was too big for github so I hope this is ok!
https://files.catbox.moe/qgjai2.mov

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment] 2023-12-09 15:46
Duplicate of #33, #30 and #48

**Closed by boylett** 2023-12-09 15:46 UTC
Labels: bug
