### ISSUE TITLE
[BUG] Negative Award Inventory

### ISSUE THREAD

**Issue by CHELRYv** [Sheezy-Art/sheezy-hub#536] opened 2024-04-10 12:21 UTC
**Describe the Issue**
tried to give someone one award, clicked on “give award” repeatedly, and it led to me giving them 3 of the same award at once. I only had 2 in my inventory so now I have -1. With -1, I am able to give people the award basically unlimited. I tested this once just to see what would happen, no intent to abuse it and will not give the award away again until my inventory is normal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to give someone an award.
2. Select your award as normal, but then when you go to give the award, click the give award button multiple times before it loads. This is especially easy to do by accident if you have slow connection and assume the previous click didn’t register.
3. You have now given multiple of the same award at once, possibly more than you even have. This can lead to having a negative amount of awards which effectively allows you an infinite award inventory for that award.

**Expected Behaviour**
One award is given, regardless of how many times the ‘Give Award’ button is clicked.

**Screenshots**
https://filegarden.com/users/65f6fe9a0fee6518170f6987/garden/#ZhaDBlLLjRCJOvIa

**Device**
- Type: Smartphone
- OS: iOS
- Browser: Firefox 
- Version: Firefox (iOS) version 124.3

**Comment by CHELRYv** [comment] 2024-04-10 16:06
Another user experienced the same bug, with the same award. Colour Instinct. Not sure if it’s just a bug with that particular award or not but it’s worth noting both instances I’ve seen were with the same one.

**Comment by xnyoom** [comment] 2024-04-10 23:15
This is being tracked privately. Gonna close this as a duplicate, though it's not your fault since you had no way of knowing.

Duplicate of https://github.com/Sheezy-Art/sheezy-security/issues/11

**Closed by xnyoom** 2024-04-10 23:15 UTC
Labels: bug

**Comment by xnyoom** [comment] 2024-04-10 23:16
Thanks for reporting!
