### ISSUE TITLE
[BUG] Journals of non-followed personas appear in journal feed

### ISSUE THREAD

**Issue by hasnogame** [Sheezy-Art/sheezy-hub#324] opened 2024-01-16 14:54 UTC
**Describe the Bug**
Journals of personas you do not follow which exist under a followed main account show up in the "JOURNALS FROM PEOPLE YOU FOLLOW" feed. If clicking on the journal title the URL will have the username of the persona's parent account.

**To Reproduce**
1. Go to the Sheezy main page
2. Scroll down to "JOURNALS FROM PEOPLE YOU FOLLOW"
4. If there is a recent journal from a persona you do not follow which exists under an account that you do follow, it will show up in the list
5. Click on the title of the journal which will bring you to the URL for the journal. The username in the URL will point to the journal as if it was from the main account instead of the persona which exists under it

**Expected Behaviour**
Journals of users you do not follow, persona or not, should not show up in the follower journal feed.

**Screenshots**
![Screenshot_20240116-093107](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/61f238c4-2590-4539-aa14-a3cef55fc648)
![Screenshot_20240116-093625](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/13dc7c9a-ca52-44de-bcaf-be2782defc13)
Malformed URL in feed: https://sheezy.dev/kryxyo/journal/something-in-me-hasnt-been-the-same
Actual URL of journal: https://sheezy.dev/kryxyo/persona/krys/journal/something-in-me-hasnt-been-the-same

**Device**
- Type: Pixel 4a 5G
 - OS: Android
 - Browser: Firefox Android
 - Version: 121.1.0 (Build #2015996455), 62d5117f79+
GV: 121.0.1-20240108143603
AS: 121.0

**Comment by boylett** [comment] 2024-01-16 15:03
Duplicate of #322. Thanks for the report though! :)

**Closed by boylett** 2024-01-16 15:03 UTC
Labels: bug
