### ISSUE TITLE
[BUG] Custom feed duplicated itself and turned into a profile link

### ISSUE THREAD

**Issue by RainyJackalope** [Sheezy-Art/sheezy-hub#385] opened 2024-02-04 20:56 UTC
**Describe the Bug**
I was making some custom feeds today, and I went to make one for my friends by calling it "FRIENDS" and adding each person I wanted on it by username. I changed nothing else and added no tags. When I submitted it, it took me to a page saying `"@feed's profile could not be found"`. It also made two feeds for FRIENDS. The second one works as a feed but the first acts as a broken profile link every time.

An update for after I had written most of this up: after I got my screenshots and information together, I tried deleting the functioning FRIENDS feed to see if it would remove both. It removed the working one but not the one that links to a profile. I cannot seem to get rid of that at all as there is no option to edit it.

**To Reproduce**

I am not entirely sure if it can be reproduced or if it is a highly specific issue, but I will try and see.

What I did initially was:

1. Make a new feed
2. Title it FRIENDS
3. Add the following users to the feed in this exact order: `@rocky @yougotta @gr8gamer @agentcricket @crochet_derg @sootychinchilla`

**Expected Behaviour**
I expected to make a custom feed with only works my friends post that shows artworks specifically uploaded by them.

**Screenshots**
Here's the settings for the feed and usernames:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/114519699/7e6ef4c5-47f1-4839-b39e-e917415c3d65)

I did not change any of the toggles or alter anything else at all.
When I click the first feed, it takes me to this page:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/114519699/34e51dd9-1c23-4d17-b4b5-660aa6ec8a92)

The URL for that page is https://sheezy.art/feed/friends
The URL for the working Friends feed is: https://sheezy.art/feed/friends-1

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0

**Comment by RainyJackalope** [comment] 2024-02-04 21:26
I made a new feed with the same parameters, except I called it "Friend Art" and it works just as expected.
Trying again by calling one FRIENDS specifically in case that somehow is causing any trouble does not repeat the result, or at least does not every time, so the exact conditions for it occurring are not known to me. My second FRIENDS feed is once again perfectly fine and functional, but the other one remains and continues to act as a profile link for some reason.

I made sure to add the exact same users in the exact same order as well just to keep things consistent.

**Comment by boylett** [comment] 2024-02-05 14:20
Fixed by [#ceb385e](https://github.com/Sheezy-Art/sheezy.art/commit/ceb385e113a0dabdca17c56609910b64612a936e)

For future reference - this is caused by the routing engine thinking that `feed` is a username. I overrode the engine for the main `/feed` page, but not other user-related pages like `/friends`, `/gallery`, `/journal` etc. This is now fixed.

**Closed by boylett** 2024-02-05 14:20 UTC
Labels: bug
