### ISSUE TITLE
[BUG] Gallery block should show most recent "likes", shows most recent submissions

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#285] opened 2024-01-07 05:36 UTC
**Describe the Bug**
Customizing the profile block to show "most recent favorites" shows the most recent submissions - not likes or from people you follow, it's site-wide submissions.

**To Reproduce**
1. Go to profile
2. View gallery block which is set to "most recent favorites"
3. Compare to most recently uploaded submissions

**Expected Behaviour**
Most recent favorites in the gallery block should be showing the most recent "liked" posts 

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/387d0e17-4b4e-42d1-90eb-172df60f15e6)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/08ed3fb0-a58e-46fc-bb7e-798fe8ecc485)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/5a790323-0d45-4c5c-91af-a2521ff46f42)
First screenshot is the gallery block on my profile which shows the most recent submissions, second screenshot is the block settings, third screenshot is the most recent submissions which show up in the block

**Device**
- Type: desktop
- OS: windows
- Browser: firefox
- Version: Version 121.0 (64-bit)

**Comment by punkalope** [comment] 2024-01-09 10:33
Fixed + duplicate of https://github.com/Sheezy-Art/sheezy-hub/issues/273 :)

**Closed by punkalope** 2024-01-09 10:33 UTC
Labels: bug
