### ISSUE TITLE
[BUG] Upload page problems

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#104] opened 2023-12-18 18:27 UTC
**Describe the Bug**
When you go to upload something new, the thing you uploaded last (Since staff testing was opened) is still there. Clicking the + button to do a second upload does nothing. Deleting the draft deletes whatever you uploaded from your gallery

**To Reproduce**
1. Go to Upload after you've uploaded something
2. Your previous upload is still there
3. Deleting the draft of what was already uploaded deletes the piece from your gallery
4. Clicking the plus button for multiple uploads does nothing

**Expected Behaviour**
A blank page for a new upload after previous submissions were successful

**Screenshots**

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment] 2023-12-18 19:42
Duplicate of #60

**Closed by boylett** 2023-12-18 19:42 UTC
Labels: duplicate
